### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [lalalilu/nunu#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by lalalilu** [comment]
Hi! Thank you so much for your feedback!

I believe I figured it out and I made the changes accordingly.

What do you think?

**Comment by BillyMassey** [comment]
Looks Awesome! Great Job 👍
